server:
  port: 8080
  servlet:
    context-path: /frankit

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frankit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        show_sql: false
        format_sql: true
        highlight_sql: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: Dp9rK6hWy3ZlBp4Sj5FvRu7XyQ8tYsN4Vc5GqKn8HtXrJcVqPiM
  access-token-expire-time: 43200000
