INSERT INTO select_option
VALUES
(null, '브랜드 로고 추가'),
(null, 'SMALL SIZE'),
(null, 'MEDIUM SIZE'),
(null, 'LARGE SIZE'),
(null, 'EXTRA-LARGE SIZE'),
(null, '한국어'),
(null, '영어'),
(null, '일본어'),
(null, '종이'),
(null, '플라스틱'),
(null, '친환경 플라스틱'),
(null, '뼈'),
(null, '순살'),
(null, '1인용'),
(null, '2인용'),
(null, '3인용'),
(null, '4인용'),
(null, '빨강'),
(null, '파랑'),
(null, '검정'),
(null, '화이트'),
(null, '그레이');